# coding: utf-8

"""
    Pastel Network API Gateway

    Pastel Network’s Gateway provides Web3 developers with easy, robust, and reliable access to the Pastel Network and its underlying protocols via a lightweight, centralized service.<br/> For more information on Pastel Network, review our <a href=https://docs.pastel.network/introduction/pastel-overview>documentation</a>.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pastel_gateway_sdk.api.collection_api import CollectionApi


class TestCollectionApi(unittest.TestCase):
    """CollectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CollectionApi()

    def tearDown(self) -> None:
        pass

    def test_collection_create_nft_collection(self) -> None:
        """Test case for collection_create_nft_collection

        Create Nft Collection
        """
        pass

    def test_collection_create_sense_collection(self) -> None:
        """Test case for collection_create_sense_collection

        Create Sense Collection
        """
        pass

    def test_collection_get_all_nft_collections(self) -> None:
        """Test case for collection_get_all_nft_collections

        Get All Nft Collections
        """
        pass

    def test_collection_get_all_sense_collections(self) -> None:
        """Test case for collection_get_all_sense_collections

        Get All Sense Collections
        """
        pass

    def test_collection_get_nft_collections_by_collection_id(self) -> None:
        """Test case for collection_get_nft_collections_by_collection_id

        Get Nft Collections By Collection Id
        """
        pass

    def test_collection_get_sense_collections_by_collection_id(self) -> None:
        """Test case for collection_get_sense_collections_by_collection_id

        Get Sense Collections By Collection Id
        """
        pass


if __name__ == '__main__':
    unittest.main()
