# coding: utf-8

"""
    Pastel Network API Gateway

    Pastel Network’s Gateway provides Web3 developers with easy, robust, and reliable access to the Pastel Network and its underlying protocols via a lightweight, centralized service.<br/> For more information on Pastel Network, review our <a href=https://docs.pastel.network/introduction/pastel-overview>documentation</a>.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
from pastel_gateway_sdk import AccountApi
from .base_test import BaseTestCase


class TestAccountApi(BaseTestCase):
    """AccountApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        await super().asyncSetUp()
        self.api: AccountApi = self.client.account_api

    async def test_account_my_total_balance(self) -> None:
        """Test case for account_my_total_balance

        My Total Balance
        """
        balance = await self.api.account_my_total_balance()
        self.assertIsNotNone(balance)

    async def test_account_set_balance_limit(self) -> None:
        """Test case for account_set_balance_limit

        Set Balance Limit
        SUPER ADMIN ONLY!!!
        """
        pass

    async def test_account_total_balances(self) -> None:
        """Test case for account_total_balances

        Total Balances
        SUPER ADMIN ONLY!!!
        """
        pass

    async def test_account_pastelid_claiming_step1(self) -> None:
        """Test case for account_pastelid_claiming_step1

        Pastelid Claiming Step 1
        """
        pass

    async def test_account_pastelid_claiming_step2(self) -> None:
        """Test case for account_pastelid_claiming_step2

        Pastelid Claiming Step 2
        """
        pass


if __name__ == '__main__':
    unittest.main()
