# coding: utf-8

"""
    Pastel Network API Gateway

    Pastel Network’s Gateway provides Web3 developers with easy, robust, and reliable access to the Pastel Network and its underlying protocols via a lightweight, centralized service.<br/> For more information on Pastel Network, review our <a href=https://docs.pastel.network/introduction/pastel-overview>documentation</a>.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from pastel_gateway_sdk.models.req_status import ReqStatus

class TestReqStatus(unittest.TestCase):
    """ReqStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReqStatus(self):
        """Test ReqStatus"""
        # inst = ReqStatus()

if __name__ == '__main__':
    unittest.main()
