# coding: utf-8

"""
    Pastel Network API Gateway

    Pastel Network’s Gateway provides Web3 developers with easy, robust, and reliable access to the Pastel Network and its underlying protocols via a lightweight, centralized service.<br/> For more information on Pastel Network, review our <a href=https://docs.pastel.network/introduction/pastel-overview>documentation</a>.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from pastel_gateway_sdk.api.admin_api import AdminApi
from .base_test import BaseTestCase


class TestAdminApi(BaseTestCase):
    """AdminApi unit test stubs"""

    def test_create_client_api_v1_admin_create_client_post(self) -> None:
        """Test case for create_client_api_v1_admin_create_client_post

        Create Client
        """
        pass


if __name__ == '__main__':
    unittest.main()
