# coding: utf-8

"""
    Pastel Network API Gateway

    Pastel Network’s Gateway provides Web3 developers with easy, robust, and reliable access to the Pastel Network and its underlying protocols via a lightweight, centralized service.<br/> For more information on Pastel Network, review our <a href=https://docs.pastel.network/introduction/pastel-overview>documentation</a>.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from pastel_gateway_sdk.api.key_auth_api import KeyAuthApi
from .base_test import BaseTestCase


class TestKeyAuthApi(BaseTestCase):
    """KeyAuthApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        await super().asyncSetUp()
        self.api = KeyAuthApi()

    def test_key_authentication_clear_wallet_key(self) -> None:
        """Test case for key_authentication_clear_wallet_key

        Clear Wallet Key
        """
        pass

    def test_key_authentication_create_user(self) -> None:
        """Test case for key_authentication_create_user

        Create User
        """
        pass

    def test_key_authentication_login_get(self) -> None:
        """Test case for key_authentication_login_get

        Get Login With Key Params
        """
        pass

    def test_key_authentication_login_post(self) -> None:
        """Test case for key_authentication_login_post

        Login With Key
        """
        pass

    def test_key_authentication_set_wallet_key(self) -> None:
        """Test case for key_authentication_set_wallet_key

        Set Wallet Key
        """
        pass


if __name__ == '__main__':
    unittest.main()
