# coding: utf-8

"""
    Pastel Network API Gateway SDK

    Pastel Network’s Gateway provides Web3 developers with easy, robust, and reliable access to the Pastel Network and its underlying protocols via a lightweight, centralized service.<br/> For more information on Pastel Network, review our <a href=https://docs.pastel.network/introduction/pastel-overview>documentation</a>.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "pastel-gateway-sdk"
VERSION = "0.0.9"
PYTHON_REQUIRES = ">=3.9"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "aiohttp >= 3.0.0",
    "aiohttp-retry >= 2.8.3",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Pastel Network Gateway SDK",
    author="Pastel Network Team",
    author_email="team@pastel.network",
    url="https://github.com/pastelnetwork/gateway-sdk-py.git",
    keywords=["Pastel Network Gateway SDK"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Pastel Network’s Gateway provides Web3 developers with easy, robust, and reliable access to the Pastel Network 
    and its underlying protocols via a lightweight, centralized service.
    For more information on Pastel Network, review our documentation  https://docs.pastel.network/introduction/pastel-overview.
    """,  # noqa: E501
    package_data={"pastel_gateway_sdk": ["py.typed"]},
)
